name: Maven Clean Build

on:
  #  push:
  #    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Maven Clean Build
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
